# $Id: Makefile 780 2010-01-23 23:48:29Z wkliao $
#
#	Makefile for netcdf man
#

include ../macros.make

PACKING_LIST	= Makefile	\
		  netcdf.m4

GARBAGE         = pnetcdf.3

all:

test:

install:

uninstall:

include ../rules.make
